name: Run API Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests
        run: mvn clean verify -DskipTests=false

      - name: List generated files (for debugging)
        run: |
          ls -R target
          ls -R target/cucumber-reports || true
          ls -R target/cucumber-json || true

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v4 
        if: always()
        with:
          name: cucumber-report
          path: target/cucumber-reports

      - name: Upload Test Results
        uses: actions/upload-artifact@v4  
        if: always()
        with:
          name: test-results
          path: target/surefire-reports
