name: Run API Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11 (recommended for stability)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Create required directories
        run: mkdir -p target/cucumber-json target/cucumber-reports

      - name: Run tests with debug output
        run: |
          mvn clean test -Dcucumber.plugin="html:target/cucumber-reports/cucumber.html,json:target/cucumber-json/cucumber.json" -e -X

      - name: Generate Cucumber reports
        run: mvn cucumber-reporting:generate

      - name: Verify generated files
        run: |
          echo "Contents of target/cucumber-json:"
          ls -la target/cucumber-json/
          echo "Contents of target/cucumber-reports:"
          ls -la target/cucumber-reports/

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/cucumber-reports/
            target/cucumber-json/
            target/surefire-reports/
